### PR TITLE
Dramatically reduce the size of browserified code by using only the parts of crypto needed

### PR DESCRIPTION
**Pull request by grempe**
Existing code bakes in all of node crypto lib. Instead use:

create-hash:
https://github.com/crypto-browserify/createHash

randombytes:
https://github.com/crypto-browserify/randombytes

Both are shims around the crypto libs in node, and in the browser use native functions.

This reduces the compiled browserify output of 'jsrp-browser.js' from
636814 bytes to 250336 bytes. A massive reduction for browser users
with no change in API, functionality, or security.

### CODE REVIEW

**Comment by alax** [comment]
Looks great, thanks!

**Comment by grempe** [comment]
Awesome, thanks for the quick response.  Would you mind cutting a new browserify release so I can point to the new smaller file?

**Comment by alax** [comment]
Done! See https://github.com/alax/jsrp/releases/tag/0.2.2

**Comment by grempe** [comment]
Excellent.  Thx!

**Comment by grempe** [comment]
FYI, this newly thin and trim code is running on my demo site now.

https://sirp-demo.herokuapp.com/index.html

**Pull request merged**
